
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import axios from 'axios';
import * as XLSX from 'xlsx';
import API_BASE_URL from './apiBase.js';
import './LeadCRM.css';
import { Search, Plus, Upload, RefreshCw, Phone, Mail, CalendarClock, MessageCircle, CheckCircle2, Circle, X, Save, Trash2, Activity, Users, TrendingUp, Clock3, Building2, ClipboardCheck } from 'lucide-react';

const API=API_BASE_URL;
const gold='#d3bfa2', muted='#9a9a9a', border='#282522', panel='#11110f';
const statuses=['New','Contacted','Demo Scheduled','Demo Completed','Proposal Sent','Negotiation','Won','Lost','Onboarding','Live'];
const checklistDefaults=['Business profile collected','Menu and pricing received','QR/menu setup completed','Owner and staff trained','WhatsApp / customer workflow configured','Billing and payment verified','Go-live checklist signed off'];
const emptyLead={businessName:'',contactName:'',phone:'',email:'',city:'Kolhapur',area:'',businessType:'Restaurant',source:'Manual',status:'New',priority:'Medium',assignedTo:'',notes:'',nextFollowUpAt:'',whatsappOptIn:false};
const inp={width:'100%',padding:'10px 11px',borderRadius:9,border:`1px solid ${border}`,background:'#0b0b0a',color:'#eee',outline:'none',fontSize:12};
const btn={display:'inline-flex',alignItems:'center',justifyContent:'center',gap:7,padding:'9px 12px',borderRadius:9,border:`1px solid ${border}`,background:'#171614',color:'#e8e2d8',fontSize:12,fontWeight:650,cursor:'pointer'};
const card={background:panel,border:`1px solid ${border}`,borderRadius:14};
export default function LeadCRM(){
 const [leads,setLeads]=useState([]),[counts,setCounts]=useState({}),[summary,setSummary]=useState({}),[notifications,setNotifications]=useState([]);
 const [loading,setLoading]=useState(true),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState(''),[assignedFilter,setAssignedFilter]=useState('');
 const [selected,setSelected]=useState(null),[activities,setActivities]=useState([]),[activityText,setActivityText]=useState(''),[activityType,setActivityType]=useState('note'),[activityDue,setActivityDue]=useState('');
 const [modal,setModal]=useState(false),[form,setForm]=useState(emptyLead),[saving,setSaving]=useState(false),[toast,setToast]=useState(''),[importing,setImporting]=useState(false),[checklist,setChecklist]=useState([]);
 const flash=msg=>{setToast(msg);setTimeout(()=>setToast(''),3200)};
 const fetchSeq=useRef(0); // typing in the search box fires a request per keystroke; only the latest response may update the list
 const fetchAll=useCallback(async()=>{const mySeq=++fetchSeq.current;setLoading(true);try{const [l,s,n]=await Promise.all([axios.get(`${API}/crm/leads`,{params:{q:query,status:statusFilter,assignedTo:assignedFilter}}),axios.get(`${API}/crm/summary`),axios.get(`${API}/crm/notifications`)]);if(mySeq!==fetchSeq.current)return;setLeads(l.data.leads||[]);setCounts(l.data.counts||{});setSummary(s.data||{});setNotifications(n.data||[])}catch(e){if(mySeq===fetchSeq.current)flash(e.response?.data?.error||'Could not load CRM data. Check backend connection.')}finally{if(mySeq===fetchSeq.current)setLoading(false)}},[query,statusFilter,assignedFilter]);
 useEffect(()=>{fetchAll()},[fetchAll]);
 const loadActivities=async lead=>{setSelected(lead);setChecklist(lead.onboarding?.length ? lead.onboarding : checklistDefaults.map(label=>({label,done:false})));try{const r=await axios.get(`${API}/crm/leads/${lead._id}/activities`);setActivities(r.data||[])}catch{setActivities([])}};
 const saveLead=async()=>{if(!form.businessName.trim()){flash('Business name is required');return}if(form.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)){flash('Enter a valid email address');return}if(form.nextFollowUpAt && Number.isNaN(new Date(form.nextFollowUpAt).getTime())){flash('Choose a valid follow-up date');return}setSaving(true);try{const payload={...form,nextFollowUpAt:form.nextFollowUpAt?new Date(form.nextFollowUpAt).toISOString():null};if(form._id)await axios.patch(`${API}/crm/leads/${form._id}`,payload);else await axios.post(`${API}/crm/leads`,payload);setModal(false);setForm(emptyLead);await fetchAll();flash('Lead saved')}catch(e){flash(e.response?.data?.error||'Could not save lead')}finally{setSaving(false)}};
 const updateLead=async(id,data)=>{try{const r=await axios.patch(`${API}/crm/leads/${id}`,data);setLeads(p=>p.map(x=>x._id===id?r.data:x));if(selected?._id===id)setSelected(r.data);await fetchAll()}catch(e){flash(e.response?.data?.error||'Update failed')}};
 const addActivity=async()=>{if(!selected||!activityText.trim())return;try{await axios.post(`${API}/crm/leads/${selected._id}/activities`,{summary:activityText,type:activityType,dueAt:activityDue?new Date(activityDue).toISOString():undefined});setActivityText('');setActivityDue('');await loadActivities(selected);await fetchAll();flash('Activity recorded')}catch(e){flash(e.response?.data?.error||'Could not save activity')}};
 const toggleChecklist=async index=>{const next=checklist.map((x,i)=>i===index?{...x,done:!x.done,completedAt:!x.done?new Date().toISOString():null}:x);setChecklist(next);try{const r=await axios.patch(`${API}/crm/leads/${selected._id}`,{onboarding:next});setSelected(r.data);setLeads(p=>p.map(x=>x._id===selected._id?r.data:x))}catch{flash('Could not save onboarding progress. Please retry.')}};
 const importFile=async file=>{if(!file)return;setImporting(true);try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const sheetName=wb.SheetNames.find(n=>/master\s*[-–]?\s*all/i.test(n))||wb.SheetNames.find(n=>/lead/i.test(n))||wb.SheetNames[0];const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{defval:''});const mapped=rows.map(r=>{const norm={};Object.entries(r).forEach(([k,v])=>norm[k.toLowerCase().trim().replace(/[^a-z0-9]/g,'')]=v);return {businessName:norm.businessname||norm.business||norm.restaurantname||norm.restaurant||norm.name||norm.company||'',contactName:norm.contactname||norm.ownername||norm.owner||norm.contact||norm.contactperson||norm.decisionmaker||'',phone:String(norm.phone||norm.mobile||norm.contactnumber||norm.mobilenumber||''),email:norm.email||norm.emailaddress||'',city:norm.city||'Kolhapur',area:norm.area||norm.locality||norm.location||norm.address||'',businessType:norm.businesstype||norm.category||norm.type||'Restaurant',status:(()=>{const s=String(norm.status||norm.salesstage||'New').toLowerCase();if(s.includes('live'))return 'Live';if(s.includes('onboard'))return 'Onboarding';if(s.includes('won')||s.includes('closed'))return 'Won';if(s.includes('lost'))return 'Lost';if(s.includes('negotiat'))return 'Negotiation';if(s.includes('proposal'))return 'Proposal Sent';if(s.includes('demo')&&s.includes('complete'))return 'Demo Completed';if(s.includes('demo'))return 'Demo Scheduled';if(s.includes('contact'))return 'Contacted';return 'New'})(),priority:(()=>{const p=String(norm.priority||'').toLowerCase();return p.includes('p1')||p.includes('premium')||p.includes('strong')||p.includes('high')?'High':p.includes('p4')||p.includes('standard')?'Low':'Medium'})(),assignedTo:norm.assignedto||norm.leadowner||norm.ownerassigned||'',nextFollowUpAt:norm.nextfollowupdate||'',notes:norm.notes||norm.leadnotes||norm.remarks||norm.suggestedpratyekshapitch||'',source:norm.source||'Excel Import'}}).filter(x=>x.businessName);if(!mapped.length)throw new Error('No business-name column found in the first sheet');const tot={created:0,updated:0,skipped:0};for(let i=0;i<mapped.length;i+=500){const r=await axios.post(`${API}/crm/import`,{leads:mapped.slice(i,i+500)});tot.created+=r.data.created||0;tot.updated+=r.data.updated||0;tot.skipped+=r.data.skipped||0} /* chunked: one request over the server's 2,500-row / 2 MB limit failed the whole import */ flash(`Import complete · ${tot.created} added · ${tot.updated} updated · ${tot.skipped} skipped`);await fetchAll()}catch(e){flash(e.response?.data?.error||e.message||'Import failed')}finally{setImporting(false)}};
 const whatsapp=lead=>{if(!lead.phone){flash('Add a phone number first');return}let phone=lead.phone.replace(/\D/g,'');if(phone.length===10)phone='91'+phone;const text=`Hi ${lead.contactName||lead.businessName}, I'm reaching out from PRATYEKSHa. We help restaurants improve customer experience, digital menus and repeat visits. Would you be open to a quick demo?`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')};
 const dueLeads=useMemo(()=>leads.filter(l=>l.nextFollowUpAt&&new Date(l.nextFollowUpAt)<=new Date()&&l.status!=='Won'&&l.status!=='Lost'),[leads]);
 return <div className="pr-crm" style={{height:'100%',minHeight:0,overflowY:'auto',padding:'22px clamp(14px,2.4vw,32px) 42px',color:'#eae7e0',fontFamily:'Inter,system-ui,sans-serif'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,flexWrap:'wrap',marginBottom:22}}>
   <div><div style={{fontSize:10,letterSpacing:2.2,color:gold,fontWeight:800,textTransform:'uppercase',marginBottom:7}}>Growth workspace · Kolhapur</div><h1 style={{fontSize:'clamp(24px,3vw,32px)',letterSpacing:-1,margin:0,fontWeight:750}}>Lead CRM<span style={{color:gold}}>.</span></h1><p style={{color:muted,fontSize:12,marginTop:7}}>From first conversation to restaurant go-live — one clear pipeline.</p></div>
   <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><label style={{...btn,cursor:'pointer'}}><Upload size={14}/>{importing?'Importing…':'Import Excel'}<input type="file" accept=".xlsx,.xls,.csv" hidden disabled={importing} onChange={e=>{importFile(e.target.files?.[0]);e.target.value=''}}/></label><button style={{...btn}} onClick={fetchAll}><RefreshCw size={14}/> Refresh</button><button style={{...btn,background:gold,color:'#17130d',borderColor:gold}} onClick={()=>{setForm(emptyLead);setModal(true)}}><Plus size={15}/> Add lead</button></div>
  </div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10,marginBottom:18}}>
   {[['Total leads',summary.total,Users],['Follow-ups due',summary.due,Clock3],['Won',summary.won,TrendingUp],['Onboarding',summary.onboarding,ClipboardCheck],['Live clients',summary.live,CheckCircle2]].map(([label,val,Icon])=><div key={label} style={{...card,padding:15,background:'linear-gradient(145deg,#151410,#0f0f0d)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',color:muted,fontSize:11}}>{label}<Icon size={15} color={gold}/></div><div style={{fontSize:27,fontWeight:750,marginTop:9,letterSpacing:-1}}>{val??0}</div><div style={{height:2,marginTop:12,background:'#24211c',borderRadius:4}}><div style={{height:2,width:`${Math.min(100,(Number(val||0)/Math.max(1,summary.total||1))*100)}%`,background:gold,borderRadius:4}}/></div></div>)}
  </div>
  {dueLeads.length>0&&<div style={{...card,padding:'12px 15px',marginBottom:14,borderColor:'#685239',display:'flex',alignItems:'center',gap:10}}><CalendarClock size={17} color={gold}/><div style={{fontSize:12,flex:1}}><b>{dueLeads.length} follow-up{dueLeads.length>1?'s':''} due</b><span style={{color:muted}}> — prioritise these leads today.</span></div><button style={btn} onClick={()=>{setStatusFilter('');setQuery('')}}>Review</button></div>}
  <div style={{display:'grid',gridTemplateColumns:selected?'minmax(0,1.25fr) minmax(320px,.8fr)':'1fr',gap:14,alignItems:'start'}}>
   <section style={{...card,overflow:'hidden',minWidth:0}}>
    <div style={{padding:14,display:'flex',gap:8,flexWrap:'wrap',borderBottom:`1px solid ${border}`}}><div style={{...inp,display:'flex',alignItems:'center',gap:8,flex:1,minWidth:160}}><Search size={15} color={muted}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search business, contact, phone…" style={{border:0,outline:0,background:'transparent',color:'#eee',width:'100%',fontSize:12}}/></div><select style={{...inp,width:'auto',minWidth:140}} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">All pipeline stages</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><input style={{...inp,width:145}} value={assignedFilter} onChange={e=>setAssignedFilter(e.target.value)} placeholder="Assigned to…"/></div>
    <div className="pr-crm-table-wrap" style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12,minWidth:630}}><thead><tr style={{color:muted,textAlign:'left',fontSize:10,textTransform:'uppercase',letterSpacing:1,background:'#0d0d0b'}}>{['Business / contact','Stage','Owner','Next follow-up',''].map(x=><th key={x} style={{padding:'12px 14px',fontWeight:650,borderBottom:`1px solid ${border}`}}>{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="5" style={{padding:30,textAlign:'center',color:muted}}>Loading pipeline…</td></tr>:leads.length===0?<tr><td colSpan="5" style={{padding:35,textAlign:'center',color:muted}}>No leads found. Add one or import your Excel tracker.</td></tr>:leads.map(l=><tr key={l._id} onClick={()=>loadActivities(l)} style={{cursor:'pointer',background:selected?._id===l._id?'rgba(211,191,162,.06)':'transparent',borderBottom:`1px solid #1d1c19`}}><td style={{padding:'13px 14px',maxWidth:210}}><div style={{fontWeight:700,color:'#f0ece4',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{l.businessName}</div><div style={{fontSize:10.5,color:muted,marginTop:4}}>{l.contactName||'Contact not added'}{l.city?` · ${l.city}`:''}</div></td><td style={{padding:'13px 8px'}}><select value={l.status} onClick={e=>e.stopPropagation()} onChange={e=>updateLead(l._id,{status:e.target.value})} style={{...inp,width:142,padding:'6px 7px',fontSize:10.5}}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td style={{padding:'13px 8px',color:muted}}>{l.assignedTo||'Unassigned'}</td><td style={{padding:'13px 8px',color:l.nextFollowUpAt&&new Date(l.nextFollowUpAt)<new Date()?'#d9a26e':muted,whiteSpace:'nowrap'}}>{l.nextFollowUpAt?new Date(l.nextFollowUpAt).toLocaleDateString('en-IN'):'—'}</td><td style={{padding:'13px 12px',whiteSpace:'nowrap'}}><button title="WhatsApp" onClick={e=>{e.stopPropagation();whatsapp(l)}} style={{...btn,padding:7,color:gold}}><MessageCircle size={14}/></button></td></tr>)}</tbody></table></div>
    <div style={{padding:'10px 14px',borderTop:`1px solid ${border}`,display:'flex',justifyContent:'space-between',color:muted,fontSize:10.5}}><span>{leads.length} records shown · {Object.values(counts).reduce((a,b)=>a+b,0)} total</span><span>Changes save directly</span></div>
   </section>
   {selected&&<aside style={{...card,overflow:'hidden',minWidth:0}}><div style={{padding:16,borderBottom:`1px solid ${border}`,background:'linear-gradient(130deg,#191711,#10100e)'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><div style={{fontSize:9,color:gold,letterSpacing:1.5,fontWeight:800,textTransform:'uppercase'}}>Lead workspace</div><h2 style={{fontSize:19,margin:'7px 0 4px',letterSpacing:-.5}}>{selected.businessName}</h2><div style={{fontSize:11,color:muted}}>{selected.businessType} · {selected.area||selected.city||'Location pending'}</div></div><button style={{...btn,padding:6,alignSelf:'flex-start'}} onClick={()=>setSelected(null)}><X size={15}/></button></div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:13}}>{selected.phone&&<a href={`tel:${selected.phone}`} style={{...btn,textDecoration:'none'}}><Phone size={13}/> Call</a>}{selected.email&&<a href={`mailto:${selected.email}`} style={{...btn,textDecoration:'none'}}><Mail size={13}/> Email</a>}<button style={{...btn,color:gold}} onClick={()=>whatsapp(selected)}><MessageCircle size={13}/> WhatsApp</button><button style={btn} onClick={()=>{setForm({...emptyLead,...selected,nextFollowUpAt:selected.nextFollowUpAt?new Date(selected.nextFollowUpAt).toISOString().slice(0,16):''});setModal(true)}}>Edit lead</button></div></div>
    <div style={{padding:15,display:'grid',gap:14,maxHeight:'calc(100vh - 310px)',overflowY:'auto'}}>
     <div><div style={{fontSize:10,color:muted,textTransform:'uppercase',letterSpacing:1,fontWeight:700,marginBottom:8}}>Follow-up planner</div><div style={{display:'grid',gridTemplateColumns:'1fr',gap:7}}><input type="datetime-local" style={inp} value={activityDue} onChange={e=>setActivityDue(e.target.value)}/><select style={inp} value={activityType} onChange={e=>setActivityType(e.target.value)}>{[['call','Call'],['whatsapp','WhatsApp'],['email','Email'],['meeting','Meeting'],['note','Note'],['followup','Follow-up']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><textarea style={{...inp,resize:'vertical',minHeight:65}} value={activityText} onChange={e=>setActivityText(e.target.value)} placeholder="Conversation summary, next step, or reminder…"/><button style={{...btn,background:gold,color:'#15120c',borderColor:gold}} onClick={addActivity}><Save size={13}/> Save activity / schedule</button></div></div>
     <div><div style={{fontSize:10,color:muted,textTransform:'uppercase',letterSpacing:1,fontWeight:700,marginBottom:9}}>Onboarding & go-live</div><div style={{display:'grid',gap:7}}>{checklistDefaults.map((label,i)=>{const item=checklist.find(x=>x.label===label)||{label,done:false};return <button key={label} onClick={()=>toggleChecklist(i)} style={{display:'flex',alignItems:'center',gap:8,textAlign:'left',padding:'8px 9px',borderRadius:8,border:`1px solid ${border}`,background:item.done?'rgba(211,191,162,.07)':'#0d0d0b',color:item.done?'#d5c6a8':'#c8c5bd',fontSize:11,cursor:'pointer'}}>{item.done?<CheckCircle2 size={15} color={gold}/>:<Circle size={15} color={muted}/>}<span style={{flex:1}}>{label}</span></button>})}</div><div style={{fontSize:10,color:muted,marginTop:8}}>{checklist.filter(x=>x.done).length} of {checklistDefaults.length} completed</div><button style={{...btn,marginTop:9,width:'100%'}} onClick={()=>updateLead(selected._id,{status:checklist.filter(x=>x.done).length===checklistDefaults.length?'Live':'Onboarding',goLiveAt:checklist.filter(x=>x.done).length===checklistDefaults.length?new Date().toISOString():null})}><CheckCircle2 size={13}/> {checklist.filter(x=>x.done).length===checklistDefaults.length?'Mark live':'Set stage to onboarding'}</button></div>
     <div><div style={{fontSize:10,color:muted,textTransform:'uppercase',letterSpacing:1,fontWeight:700,marginBottom:8}}>Activity history</div>{activities.length===0?<div style={{fontSize:11,color:muted,padding:'8px 0'}}>No activity recorded yet.</div>:activities.map(a=><div key={a._id} style={{borderLeft:`2px solid ${gold}`,padding:'2px 0 10px 10px',marginLeft:3,marginBottom:8}}><div style={{fontSize:11,color:'#e5e0d5'}}>{a.summary}</div><div style={{fontSize:9.5,color:muted,marginTop:4}}>{a.type} · {new Date(a.createdAt).toLocaleString('en-IN')}</div></div>)}</div>
     <button style={{...btn,color:'#c8896d',justifySelf:'start'}} onClick={async()=>{if(!confirm(`Delete ${selected.businessName}? This removes its CRM activity too.`))return;try{await axios.delete(`${API}/crm/leads/${selected._id}`);setSelected(null);await fetchAll();flash('Lead deleted')}catch(e){flash(e.response?.data?.error||'Delete failed')}}}><Trash2 size={13}/> Delete lead</button>
    </div>
   </aside>}
  </div>
  {notifications.filter(n=>!n.readAt).length>0&&<div style={{...card,padding:13,marginTop:14}}><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:8}}><CalendarClock size={15} color={gold}/><b style={{fontSize:12}}>Reminder inbox</b><span style={{color:muted,fontSize:10}}>{notifications.filter(n=>!n.readAt).length} unread</span></div>{notifications.filter(n=>!n.readAt).slice(0,5).map(n=><div key={n._id} style={{display:'flex',gap:8,alignItems:'center',padding:'7px 0',borderTop:`1px solid ${border}`,fontSize:11}}><span style={{flex:1}}>{n.title}: {n.message}</span><button style={{...btn,padding:'5px 8px'}} onClick={async()=>{await axios.patch(`${API}/crm/notifications/${n._id}/read`);await fetchAll()}}>Mark read</button></div>)}</div>}
  {toast&&<div style={{position:'fixed',bottom:20,right:20,zIndex:1000,padding:'12px 16px',background:'#211f19',border:`1px solid ${gold}`,borderRadius:10,color:'#f4ead8',fontSize:12,boxShadow:'0 14px 40px #0009'}}>{toast}</div>}
  {modal&&<div style={{position:'fixed',inset:0,zIndex:500,background:'#000b',backdropFilter:'blur(5px)',display:'grid',placeItems:'center',padding:14}}><div style={{...card,width:620,maxWidth:'100%',maxHeight:'92vh',overflowY:'auto',padding:20,boxShadow:'0 24px 80px #000b'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div><div style={{fontSize:9,color:gold,letterSpacing:1.6,fontWeight:800,textTransform:'uppercase'}}>Pipeline record</div><h2 style={{fontSize:20,margin:'4px 0 0'}}>{form._id?'Edit lead':'Create lead'}</h2></div><button style={btn} onClick={()=>setModal(false)}><X size={15}/></button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}>{[['businessName','Business name *'],['contactName','Contact person'],['phone','Phone / WhatsApp'],['email','Email'],['city','City'],['area','Area / locality'],['assignedTo','Assigned to'],['source','Lead source']].map(([key,label])=><label key={key} style={{fontSize:10,color:muted,display:'grid',gap:5}}>{label}<input style={inp} value={form[key]||''} onChange={e=>setForm(p=>({...p,[key]:e.target.value}))}/></label>)}<label style={{fontSize:10,color:muted,display:'grid',gap:5}}>Business type<select style={inp} value={form.businessType||'Restaurant'} onChange={e=>setForm(p=>({...p,businessType:e.target.value}))}>{['Restaurant','Cafe','Bakery','Cloud Kitchen','Hotel','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label style={{fontSize:10,color:muted,display:'grid',gap:5}}>Pipeline stage<select style={inp} value={form.status||'New'} onChange={e=>setForm(p=>({...p,status:e.target.value}))}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label style={{fontSize:10,color:muted,display:'grid',gap:5}}>Priority<select style={inp} value={form.priority||'Medium'} onChange={e=>setForm(p=>({...p,priority:e.target.value}))}>{['Low','Medium','High'].map(x=><option key={x}>{x}</option>)}</select></label><label style={{fontSize:10,color:muted,display:'grid',gap:5}}>Next follow-up<input type="datetime-local" style={inp} value={form.nextFollowUpAt||''} onChange={e=>setForm(p=>({...p,nextFollowUpAt:e.target.value}))}/></label><label style={{fontSize:10,color:muted,display:'grid',gap:5,gridColumn:'1/-1'}}>Notes<textarea style={{...inp,minHeight:80,resize:'vertical'}} value={form.notes||''} onChange={e=>setForm(p=>({...p,notes:e.target.value}))}/></label></div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button style={btn} onClick={()=>setModal(false)}>Cancel</button><button style={{...btn,background:gold,color:'#17130d',borderColor:gold}} disabled={saving} onClick={saveLead}><Save size={14}/>{saving?'Saving…':'Save lead'}</button></div></div></div>}
 </div>;
}
